<#
.SYNOPSIS
  Measures scan and analysis rates against a generated corpus, and writes the
  numbers down.

.DESCRIPTION
  Every scale claim on the board was reasoned from reading the code. This script
  is the other thing: it runs the real binary against a real corpus and records
  what actually happened, so a claim can be checked instead of believed.

  It is deliberately boring. Scan a corpus, scan it a second time, analyse it,
  print a table. No averaging over runs, no statistical smoothing - one run,
  reported honestly, with the machine and the date beside it so nobody quotes a
  number without knowing where it came from.

  SCOPE - read this before quoting anything it prints.

  * It measures the `birds-eye-scan` CLI, not the desktop app. The app does more
    work around the same core (job scheduling, progress plumbing, the UI), so
    these are floors, not the time a user waits.
  * The first scan of a corpus that was just written is NOT cold. Windows still
    has the tree in its file cache, and there is no supported way to drop that
    cache from a script without admin rights and an external tool. So the
    "first scan" column is a WARM first scan. It is a real number and a useful
    floor; it is not what a user sees opening a drive they have not touched
    today. Reboot between runs if you need the cold figure, and say which one
    you measured.
  * Analysis runs at the AllOptIn budget, which is the most expensive tier. A
    default install does less.

.PARAMETER Root
  Corpus folder to scan. Generate one with `birds-eye-bench-corpus`.

.PARAMETER Label
  Name for this row in the results table, e.g. "files-100k".

.PARAMETER Analyze
  Also run the analysis phase and time it. Off by default because on a large
  corpus it dominates the run.

.PARAMETER OutFile
  Markdown file to append the result row to. Defaults to
  `docs/benchmarks.md` beside the repo root.

.EXAMPLE
  ./scripts/bench-scale.ps1 -Root D:\bench-corpus\files-100k -Label files-100k -Analyze
#>
[CmdletBinding()]
param(
  [Parameter(Mandatory = $true)][string]$Root,
  [Parameter(Mandatory = $true)][string]$Label,
  [switch]$Analyze,
  [string]$OutFile
)

$ErrorActionPreference = 'Stop'

if (-not (Test-Path -LiteralPath $Root)) {
  throw "corpus not found: $Root. Generate one with birds-eye-bench-corpus."
}

$repo = Split-Path -Parent $PSScriptRoot
$exe = Join-Path $repo 'target\release\birds-eye-scan.exe'
if (-not (Test-Path -LiteralPath $exe)) {
  throw "build it first: cargo build --release"
}
if (-not $OutFile) { $OutFile = Join-Path $repo 'docs\benchmarks.md' }

$indexDir = Join-Path $env:TEMP 'birds-eye-bench'
New-Item -ItemType Directory -Force -Path $indexDir | Out-Null
$index = Join-Path $indexDir "$Label.sqlite"
# A stale index turns a first scan into a rescan, which is the single easiest
# way to publish a number that is wrong by an order of magnitude.
Remove-Item -Force -ErrorAction SilentlyContinue "$index", "$index-wal", "$index-shm"

function Invoke-Scan {
  param([string[]]$ExtraArgs)
  $args = @($Root, '--index', $index) + $ExtraArgs
  $sw = [System.Diagnostics.Stopwatch]::StartNew()
  $out = & $exe @args 2>&1
  $sw.Stop()
  [pscustomobject]@{
    WallMs = $sw.ElapsedMilliseconds
    Lines  = $out
  }
}

function Get-Field {
  param([object[]]$Lines, [string]$Prefix, [string]$Name)
  $line = $Lines | Where-Object { "$_" -like "$Prefix*" } | Select-Object -Last 1
  if (-not $line) { return $null }
  if ("$line" -match "$Name=([0-9.]+)") { return $Matches[1] }
  return $null
}

Write-Host "first scan  ($Label)..." -ForegroundColor Cyan
$first = Invoke-Scan -ExtraArgs @()
$files = Get-Field $first.Lines 'finished' 'files'
$bytes = Get-Field $first.Lines 'finished' 'bytes'
$unreadable = Get-Field $first.Lines 'finished' 'unreadable'
$firstRate = Get-Field $first.Lines 'finished' 'files_per_sec'

Write-Host "second scan ($Label)..." -ForegroundColor Cyan
$second = Invoke-Scan -ExtraArgs @()
$secondRate = Get-Field $second.Lines 'finished' 'files_per_sec'

$analyzeMs = ''
if ($Analyze) {
  Write-Host "analysis    ($Label)..." -ForegroundColor Cyan
  $third = Invoke-Scan -ExtraArgs @('--analyze')
  $analyzeMs = Get-Field $third.Lines 'analyzed' 'elapsed_ms'
}

$row = "| {0} | {1} | {2} | {3} | {4} | {5} | {6} | {7} | {8} |" -f `
  $Label, $files, $bytes, $unreadable, $first.WallMs, $second.WallMs, $firstRate, $secondRate, $analyzeMs

if (-not (Test-Path -LiteralPath $OutFile)) {
  New-Item -ItemType Directory -Force -Path (Split-Path -Parent $OutFile) | Out-Null
  $header = @(
    "# Measured benchmarks",
    "",
    "Generated by ``scripts/bench-scale.ps1``. One run each, not an average.",
    "Corpora are built by ``birds-eye-bench-corpus``.",
    "",
    "These measure the ``birds-eye-scan`` CLI, not the desktop app, so they are floors.",
    "Analysis runs at the AllOptIn budget, which is the most expensive tier.",
    "",
    ("Machine: {0}, {1} logical cores. Recorded {2}." -f $env:COMPUTERNAME, [Environment]::ProcessorCount, (Get-Date -Format 'yyyy-MM-dd')),
    "",
    "| corpus | files | bytes | unreadable | scan ms | rescan ms | scan files/sec | rescan files/sec | analysis ms |",
    "|---|---|---|---|---|---|---|---|---|"
  )
  Set-Content -Path $OutFile -Value $header -Encoding utf8
}
Add-Content -Path $OutFile -Value $row -Encoding utf8

Write-Host ""
Write-Host $row -ForegroundColor Green
Write-Host "appended to $OutFile"
